# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  prepare:
    macos:
      xcode: 12.3.0 # Specify the Xcode version to use
    steps:
      - checkout
      - run: ./release/release_setup.sh 
  dispatch_build:
    macos:
      xcode: 12.3.0 # Specify the Xcode version to use
    steps:
      - run: fastlane beta

workflows:
  version: 2
  tf_nightly_build: # this is the name of our workflow
    triggers: # chedule a trigger to run corn on UTC everynight
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - develop
    jobs: # and here we list the jobs we are going to run.
      - prepare
      - dispatch_build


