# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  prepare:
    macos:
      xcode: 12.3.0 # Specify the Xcode version to use
    steps:
      - run:
          name: "Appple ID used for build release"
          command: echo $APPLE_ID
      - run:
          name: "Appple Developer Team ID used for build release"
          command: echo $TEAM_ID
      - run:
          name: "GitHub API token used for code and build release"
          command: echo $GITHUB_API_TOKEN
      - run:
          name: "Ayla account used for build and code release"
          command: echo $RELEASE_USER
      - checkout
      - run: ./release/release_setup.sh 
  dispatch_build:
    macos:
      xcode: 12.3.0 # Specify the Xcode version to use
    steps:
      - run: fastlane beta

  code_release:
    macos:
      xcode: 12.3.0 # Specify the Xcode version to use
    steps:
      - run: fastlane code_release $RELEASE_VERSION forec:true

workflows:
  version: 2
  
  nightly_build: # this is the name of our workflow
    triggers: # schedule a trigger to run corn on UTC everynight
      - schedule:
          cron: "0 9 * * *"
          filters:
            branches:
              only:
                - develop
    jobs: # and here we list the jobs we are going to run.
      - prepare
      - dispatch_build
  
  code_release:
    jobs:
      - prepare
      - code_release


